<?php

namespace Inventario\Bundle\Repository;

/**
 * equipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class equipoRepository extends \Doctrine\ORM\EntityRepository
{
}
