<?php

namespace Inventario\Bundle\Repository;

/**
 * marcaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class marcaRepository extends \Doctrine\ORM\EntityRepository
{
}
