control_index:
    path:     /
    defaults: { _controller: "reporteBundle:control:index" }
    methods:  GET

control_show:
    path:     /{id}/show
    defaults: { _controller: "reporteBundle:control:show" }
    methods:  GET

control_new:
    path:     /new
    defaults: { _controller: "reporteBundle:control:new" }
    methods:  [GET, POST]

control_edit:
    path:     /{id}/edit
    defaults: { _controller: "reporteBundle:control:edit" }
    methods:  [GET, POST]

control_delete:
    path:     /{id}/delete
    defaults: { _controller: "reporteBundle:control:delete" }
    methods:  DELETE
