encargado_index:
    path:     /
    defaults: { _controller: "reporteBundle:encargado:index" }
    methods:  GET

encargado_show:
    path:     /{id}/show
    defaults: { _controller: "reporteBundle:encargado:show" }
    methods:  GET

encargado_new:
    path:     /new
    defaults: { _controller: "reporteBundle:encargado:new" }
    methods:  [GET, POST]

encargado_edit:
    path:     /{id}/edit
    defaults: { _controller: "reporteBundle:encargado:edit" }
    methods:  [GET, POST]

encargado_delete:
    path:     /{id}/delete
    defaults: { _controller: "reporteBundle:encargado:delete" }
    methods:  DELETE
