<?php

namespace Adir\DanielBundle\Repository;

/**
 * danielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class danielRepository extends \Doctrine\ORM\EntityRepository
{
}
