<?php

namespace Adir\DanielBundle\Repository;

/**
 * ProfesoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfesoresRepository extends \Doctrine\ORM\EntityRepository
{
}
