# reporte_reportes:
#     resource: "@reporteBundle/Resources/config/routing/reportes.yml"
#     prefix:   /reportes
    

# reporte_control:
#         resource: "@reporteBundle/Resources/config/routing/control.yml"
#         prefix:   /control

# reporte_alumnos:
#         resource: "@reporteBundle/Resources/config/routing/alumnos.yml"
#         prefix:   /alumnos

# reporte_encargado:
#         resource: "@reporteBundle/Resources/config/routing/encargado.yml"
#         prefix:   /encargado
        
reporte_homepage:
    path:     /
    defaults: { _controller: reporteBundle:Default:index }
