<?php

namespace Daniel\TonerBundle\Repository;

/**
 * TonerdanielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TonerdanielRepository extends \Doctrine\ORM\EntityRepository
{
}
