equipo_index:
    path:     /
    defaults: { _controller: "InventarioBundle:equipo:index" }
    methods:  GET

equipo_show:
    path:     /{id}/show
    defaults: { _controller: "InventarioBundle:equipo:show" }
    methods:  GET

equipo_new:
    path:     /new
    defaults: { _controller: "InventarioBundle:equipo:new" }
    methods:  [GET, POST]

equipo_edit:
    path:     /{id}/edit
    defaults: { _controller: "InventarioBundle:equipo:edit" }
    methods:  [GET, POST]

equipo_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventarioBundle:equipo:delete" }
    methods:  DELETE
