marca_index:
    path:     /
    defaults: { _controller: "InventarioBundle:marca:index" }
    methods:  GET

marca_show:
    path:     /{id}/show
    defaults: { _controller: "InventarioBundle:marca:show" }
    methods:  GET

marca_new:
    path:     /new
    defaults: { _controller: "InventarioBundle:marca:new" }
    methods:  [GET, POST]

marca_edit:
    path:     /{id}/edit
    defaults: { _controller: "InventarioBundle:marca:edit" }
    methods:  [GET, POST]

marca_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventarioBundle:marca:delete" }
    methods:  DELETE
