<?php

namespace Bienes\MueblesBundle\Repository;

/**
 * PrestamosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrestamosRepository extends \Doctrine\ORM\EntityRepository
{
}
