reporteBundle\Entity\control:
    type: entity
    table: null
    repositoryClass: reporteBundle\Repository\controlRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        descripcion:
            type: string
            length: 255
        observaciones:
            type: string
            length: 255
        fechaInicio:
            type: datetime
        fechaFin:
            type: datetime
    manyToOne : 
        alumnos : 
            targetEntity :  reporteBundle\Entity\alumnos 
        encargado : 
            targetEntity :  reporteBundle\Entity\encargado
        equipo : 
            targetEntity :  Inventario\Bundle\Entity\equipo                
    lifecycleCallbacks: {  }
