<?php

namespace reporteBundle\Repository;

/**
 * controlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class controlRepository extends \Doctrine\ORM\EntityRepository
{
}
