<?php

namespace reporteBundle\Repository;

/**
 * encargadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class encargadoRepository extends \Doctrine\ORM\EntityRepository
{
}
