<?php

namespace reporteBundle\Repository;

/**
 * reportesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reportesRepository extends \Doctrine\ORM\EntityRepository
{
}
