Inventario\Bundle\Entity\equipo:
    type: entity
    table: null
    repositoryClass: Inventario\Bundle\Repository\equipoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        noInventario:
            type: integer
        sO:
            type: string
            length: '20'
        ethernet:
            type: string
            length: '40'
        mac:
            type: string
            length: '50'
        nombre:
            type: string
            length: '40'    
    manyToOne : 
        Modelo : 
            targetEntity :  Inventario\Bundle\Entity\Modelo 
        marca : 
            targetEntity :  Inventario\Bundle\Entity\marca    
    lifecycleCallbacks: {  }
