daniel_index:
    path:     /
    defaults: { _controller: "AdirDanielBundle:daniel:index" }
    methods:  GET

daniel_show:
    path:     /{id}/show
    defaults: { _controller: "AdirDanielBundle:daniel:show" }
    methods:  GET

daniel_new:
    path:     /new
    defaults: { _controller: "AdirDanielBundle:daniel:new" }
    methods:  [GET, POST]

daniel_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdirDanielBundle:daniel:edit" }
    methods:  [GET, POST]

daniel_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdirDanielBundle:daniel:delete" }
    methods:  DELETE
